#!/usr/bin/env bash
# Ventra acquisition kit — operator entrypoint (generated by collector.kit.build)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
CASE_ID="${1:-CASE-UNKNOWN}"
OUT="${2:-./ventra-evidence}"
CLOUD="${VENTRA_CLOUD:-aws}"

exec ventra collect "$CLOUD" --case "$CASE_ID" --out "$OUT" "$@"
