"use client";

import { useCase } from "@/components/case-context";
import { PanelBody, PanelHeader } from "@/components/panel";
import { Button, Card, EmptyState } from "@/components/ui";
import { api } from "@/lib/api";
import { fmtTime } from "@/lib/format";
import { usePins } from "@/lib/usePins";
import { useQuery } from "@tanstack/react-query";
import { Download, FileText, Pin, Trash2 } from "lucide-react";
import { useState } from "react";

export default function ReportPage() {
  const { caseId } = useCase();
  const { pins, remove } = usePins(caseId);
  const summary = useQuery({ queryKey: ["summary", caseId], queryFn: () => api.summary(caseId) });
  const [notes, setNotes] = useState("");

  const buildMarkdown = () => {
    const s = summary.data;
    const lines: string[] = [];
    lines.push(`# Incident Report — ${caseId}`, "");
    if (s) {
      lines.push(`- **Cloud / Account:** ${s.cloud?.toUpperCase()} ${s.account_id} ${s.account_alias ? `(${s.account_alias})` : ""}`);
      lines.push(`- **Regions:** ${s.regions?.join(", ")}`);
      lines.push(`- **Collected by:** ${s.operator?.principal_arn ?? "—"}`);
      lines.push(`- **Window:** ${s.time_window?.since ?? "start"} → ${s.time_window?.until ?? "now"}`);
      lines.push(`- **Integrity:** ${s.integrity} (${s.signature_method})`);
      lines.push(`- **Events:** ${s.totals?.events} · **Principals:** ${s.totals?.principals} · **High+:** ${s.totals?.sensitive_actions}`);
      lines.push("");
    }
    if (notes.trim()) {
      lines.push("## Analyst narrative", "", notes.trim(), "");
    }
    lines.push("## Pinned evidence", "");
    if (pins.length === 0) lines.push("_No evidence pinned._");
    pins.forEach((p, i) => {
      lines.push(`### ${i + 1}. ${p.title}`);
      if (p.timestamp) lines.push(`- **Time:** ${fmtTime(p.timestamp)}`);
      if (p.detail) lines.push(`- **Detail:** ${p.detail}`);
      if (p.ref) lines.push(`- **Refs:** \`${JSON.stringify(p.ref)}\``);
      lines.push("");
    });
    lines.push("---", `_Generated by Harbor from sealed evidence package ${caseId}._`);
    return lines.join("\n");
  };

  const exportMd = () => {
    const blob = new Blob([buildMarkdown()], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${caseId}-report.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <PanelHeader
        icon={FileText}
        title="Report"
        description="Pin evidence as you investigate, then export"
        actions={
          <Button variant="primary" icon={Download} onClick={exportMd} disabled={pins.length === 0 && !notes}>
            Export Markdown
          </Button>
        }
      />
      <PanelBody className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        {/* Narrative */}
        <Card className="flex flex-col">
          <div className="border-b border-border px-4 py-3 text-sm font-semibold">Analyst narrative</div>
          <textarea
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Summarize the incident: entry, escalation, impact, and recommended actions…"
            className="min-h-[320px] flex-1 resize-none bg-transparent p-4 text-sm leading-relaxed text-fg placeholder:text-fg-subtle/60 focus:outline-none"
          />
        </Card>

        {/* Pinned evidence */}
        <Card>
          <div className="flex items-center justify-between border-b border-border px-4 py-3">
            <span className="text-sm font-semibold">Pinned evidence</span>
            <span className="chip">{pins.length}</span>
          </div>
          {pins.length === 0 ? (
            <EmptyState
              icon={Pin}
              title="Nothing pinned yet"
              description="Open any event or finding and use “Pin to report”. Pinned items appear here as immutable evidence callouts with their source reference."
            />
          ) : (
            <div className="divide-y divide-border">
              {pins.map((p) => (
                <div key={p.id} className="flex items-start gap-3 px-4 py-3">
                  <Pin className="mt-0.5 h-3.5 w-3.5 shrink-0 text-accent" />
                  <div className="min-w-0 flex-1">
                    <div className="truncate text-sm text-fg">{p.title}</div>
                    {p.timestamp && (
                      <div className="mono text-2xs text-fg-subtle">{fmtTime(p.timestamp)}</div>
                    )}
                    {p.detail && <div className="mt-0.5 text-xs text-fg-subtle">{p.detail}</div>}
                  </div>
                  <button onClick={() => remove(p.id)} className="text-fg-subtle hover:text-bad-red">
                    <Trash2 className="h-3.5 w-3.5" />
                  </button>
                </div>
              ))}
            </div>
          )}
        </Card>
      </PanelBody>
    </>
  );
}
