import type { Cloud } from "@/lib/catalog";

/** Display filename stems under ``public/icons/<cloud>/`` (must match extract-artifact-icons). */
export const ARTIFACT_ICON_LABELS: Record<string, string> = {
  account: "account",
  cloudfront: "cloudfront access logs",
  cloudtrail: "cloudtrail",
  config: "config",
  detective: "detective",
  ec2: "ec2",
  eks_audit: "eks audit",
  elb_alb: "elb alb access logs",
  guardduty: "guardduty",
  iam: "iam",
  inspector2: "inspector2",
  kms: "kms",
  lambda: "lambda",
  log_posture: "log posture",
  macie: "macie",
  route53_resolver: "route53 resolver",
  s3: "s3",
  s3_access: "s3 access logs",
  secrets: "secrets",
  securityhub: "security hub",
  vpc_flow: "vpc flow logs",
  waf: "waf",
  activity_log: "activity log",
  aks_audit: "aks audit",
  app_gateway: "app gateway access logs",
  azure_firewall: "azure firewall logs",
  defender: "defender",
  diag_posture: "diagnostic posture",
  dns: "dns",
  entra_audit: "entra audit",
  entra_directory: "entra directory",
  entra_signin: "entra signin",
  front_door: "front door access logs",
  key_vault: "key vault",
  log_analytics: "log analytics",
  nsg_flow: "nsg flow logs",
  oauth_consent: "oauth consent",
  rbac: "rbac",
  resource_graph: "resource graph",
  storage_access: "storage access logs",
  subscription: "subscription",
  unified_audit: "unified audit",
  unified_audit_search: "unified audit search",
  vnet_flow: "vnet flow logs",
  api_gateway: "api gateway",
  cloud_audit_admin: "cloud audit admin",
  cloud_audit_data: "cloud audit data",
  cloud_audit_system: "cloud audit system",
  cloud_functions: "cloud functions",
  cloud_monitoring: "cloud monitoring",
  firewall_logs: "firewall logs",
  iam_policy: "iam policy",
  load_balancer: "load balancer access logs",
  login_events: "login events",
  project: "project",
  scc_findings: "scc findings",
  vm_logs: "vm logs",
  workspace_audit: "workspace audit",
  gke_audit: "gke audit",
};

/** UI display names (proper product / acronym casing). Icon filenames stay lowercase in ``ARTIFACT_ICON_LABELS``. */
const ARTIFACT_DISPLAY_LABELS: Record<string, string> = {
  account: "Account",
  cloudfront: "CloudFront Access Logs",
  cloudtrail: "CloudTrail",
  config: "Config",
  detective: "Detective",
  ec2: "EC2",
  eks_audit: "EKS Audit",
  elb_alb: "ELB/ALB Access Logs",
  guardduty: "GuardDuty",
  iam: "IAM",
  inspector2: "Inspector2",
  kms: "KMS",
  lambda: "Lambda",
  log_posture: "Log Posture",
  macie: "Macie",
  route53_resolver: "Route53 Resolver",
  s3: "S3",
  s3_access: "S3 Access Logs",
  secrets: "Secrets Manager",
  securityhub: "Security Hub",
  vpc_flow: "VPC Flow Logs",
  waf: "WAF",
  activity_log: "Activity Log",
  aks_audit: "AKS Audit",
  app_gateway: "App Gateway Access Logs",
  azure_firewall: "Azure Firewall Logs",
  defender: "Defender for Cloud",
  diag_posture: "Diagnostic Posture",
  dns: "DNS",
  entra_audit: "Entra Audit",
  entra_directory: "Entra Directory",
  entra_signin: "Entra Sign-in",
  front_door: "Front Door Access Logs",
  key_vault: "Key Vault",
  log_analytics: "Log Analytics",
  nsg_flow: "NSG Flow Logs",
  oauth_consent: "OAuth Consent",
  rbac: "RBAC",
  resource_graph: "Resource Graph",
  storage_access: "Storage Access Logs",
  subscription: "Subscription",
  unified_audit: "Unified Audit",
  unified_audit_search: "Unified Audit Search",
  vnet_flow: "VNet Flow Logs",
  api_gateway: "API Gateway",
  cloud_audit_admin: "Cloud Audit Admin",
  cloud_audit_data: "Cloud Audit Data",
  cloud_audit_system: "Cloud Audit System",
  cloud_functions: "Cloud Functions",
  cloud_monitoring: "Cloud Monitoring",
  firewall_logs: "Firewall Logs",
  iam_policy: "IAM Policy",
  load_balancer: "Load Balancer Access Logs",
  login_events: "Login Events",
  project: "Project",
  scc_findings: "SCC Findings",
  vm_logs: "VM Logs",
  workspace_audit: "Workspace Audit",
  gke_audit: "GKE Audit",
};

export function displayArtifactLabel(collector: string): string {
  if (ARTIFACT_DISPLAY_LABELS[collector]) return ARTIFACT_DISPLAY_LABELS[collector];
  const label = ARTIFACT_ICON_LABELS[collector] ?? collector.replace(/_/g, " ");
  return label.charAt(0).toUpperCase() + label.slice(1);
}

function iconExtension(cloud: Cloud): string {
  return cloud === "azure" ? ".svg" : ".png";
}

export function artifactIconSrc(cloud: string, collector: string): string | null {
  const label = ARTIFACT_ICON_LABELS[collector];
  if (!label) return null;
  const c = cloud.toLowerCase() as Cloud;
  return `/icons/${c}/${encodeURIComponent(label)}${iconExtension(c)}`;
}
