/** Collectors with an SVG under ``public/icons/<cloud>/<collector>.svg`` (see extract-artifact-icons). */
export const ARTIFACT_ICON_LABELS: Record<string, string> = {
  account: "account",
  apigateway: "api gateway access logs",
  cloudfront: "cloudfront access logs",
  cloudtrail: "cloudtrail",
  cloudwatch: "cloudwatch",
  config: "config",
  detective: "detective",
  dynamodb_streams: "dynamodb streams",
  ec2: "ec2",
  eks_audit: "eks audit",
  elb_alb: "elb alb access logs",
  guardduty: "guardduty",
  iam: "iam",
  inspector2: "inspector2",
  kms: "kms",
  lambda: "lambda",
  lambda_logs: "lambda logs",
  log_posture: "log posture",
  macie: "macie",
  network_firewall: "network firewall",
  opensearch: "opensearch",
  route53_resolver: "route53 resolver",
  rds: "rds logs",
  s3: "s3",
  s3_access: "s3 access logs",
  secrets: "secrets",
  securityhub: "security hub",
  vpc_flow: "vpc flow logs",
  waf: "waf",
  activity_log: "activity log",
  aks_audit: "aks audit",
  app_gateway: "app gateway access logs",
  azure_firewall: "azure firewall logs",
  defender: "defender",
  diag_posture: "diagnostic posture",
  dns: "dns",
  entra_audit: "entra audit",
  entra_directory: "entra directory",
  entra_signin: "entra signin",
  front_door: "front door access logs",
  key_vault: "key vault",
  log_analytics: "log analytics",
  nsg_flow: "nsg flow logs",
  oauth_consent: "oauth consent",
  rbac: "rbac",
  resource_graph: "resource graph",
  storage_access: "storage access logs",
  bigquery_audit: "bigquery audit",
  cloud_sql: "cloud sql",
  secret_manager: "secret manager",
  subscription: "subscription",
  unified_audit: "unified audit",
  unified_audit_search: "unified audit search",
  vnet_flow: "vnet flow logs",
  api_gateway: "api gateway",
  cloud_audit_admin: "cloud audit admin",
  cloud_audit_data: "cloud audit data",
  cloud_audit_system: "cloud audit system",
  cloud_functions: "cloud functions",
  cloud_monitoring: "cloud monitoring",
  firewall_logs: "firewall logs",
  gce: "compute engine",
  iam_policy: "iam policy",
  load_balancer: "cloud load balancing logs",
  cloud_cdn: "cloud cdn access logs",
  logging_posture: "logging posture",
  login_events: "login events",
  network_posture: "network posture",
  project: "project",
  scc_findings: "scc findings",
  vm_logs: "vm logs",
  gke_audit: "gke audit",
  cloud_dns: "cloud dns",
  cloud_armor: "cloud armor",
  cloud_nat: "cloud nat",
  k8s_apiserver_audit: "API-Server Audit Logs",
  k8s_audit_posture: "audit logging posture",
  k8s_events: "kubernetes events",
  k8s_cluster_state: "cluster inventory",
  k8s_rbac: "rbac snapshot",
  k8s_container_logs: "container logs",
  k8s_kubelet_logs: "kubelet logs",
  k8s_runtime_logs: "CRI logs",
  k8s_etcd: "etcd",
  k8s_cni_logs: "cni plugin logs",
};

/** UI display names (proper product / acronym casing). */
const ARTIFACT_DISPLAY_LABELS: Record<string, string> = {
  account: "Account Context",
  apigateway: "API Gateway Access Logs",
  cloudfront: "CloudFront Access Logs",
  cloudtrail: "CloudTrail Logs",
  cloudwatch: "CloudWatch Logs",
  config: "Config Snapshot",
  detective: "Detective Investigations",
  dynamodb_streams: "DynamoDB Streams",
  ec2: "EC2 / EBS Inventory",
  eks_audit: "EKS Audit Logs",
  elb_alb: "ELB/ALB Access Logs",
  guardduty: "GuardDuty Findings",
  iam: "IAM Snapshot",
  inspector2: "Inspector Findings",
  kms: "KMS Key Inventory",
  lambda: "Lambda Inventory",
  lambda_logs: "Lambda Execution Logs",
  log_posture: "Logging Posture",
  macie: "Macie Findings",
  network_firewall: "Network Firewall Logs",
  opensearch: "OpenSearch Logs",
  route53_resolver: "Route 53 Resolver Query Logs",
  rds: "RDS Export Logs",
  s3: "S3 Inventory",
  s3_access: "S3 Access Logs",
  secrets: "Secrets Manager Inventory",
  securityhub: "Security Hub Findings",
  vpc_flow: "VPC Flow Logs",
  waf: "WAF Config & Sampled Requests",
  activity_log: "Activity Logs",
  aks_audit: "AKS Audit Logs",
  app_gateway: "App Gateway Access Logs",
  azure_firewall: "Azure Firewall Logs",
  defender: "Defender for Cloud Alerts",
  diag_posture: "Diagnostic Posture",
  dns: "DNS Query Logs",
  entra_audit: "Entra Audit Logs",
  entra_directory: "Entra Directory Snapshot",
  entra_signin: "Entra Sign-in Logs",
  front_door: "Front Door Access Logs",
  key_vault: "Key Vault Audit Logs",
  log_analytics: "Log Analytics Diagnostics",
  nsg_flow: "NSG Flow Logs",
  oauth_consent: "OAuth Consent Grants",
  rbac: "RBAC Snapshot",
  resource_graph: "Resource Graph Inventory",
  storage_access: "Storage Access Logs",
  bigquery_audit: "BigQuery Audit Logs",
  cloud_sql: "Cloud SQL Logs",
  secret_manager: "Secret Manager Access Logs",
  subscription: "Subscription Context",
  unified_audit: "M365 Unified Audit Logs",
  unified_audit_search: "M365 Unified Audit Search",
  vnet_flow: "VNet Flow Logs",
  api_gateway: "API Gateway Access Logs",
  cloud_audit_admin: "Admin Activity Audit Logs",
  cloud_audit_data: "Data Access Audit Logs",
  cloud_audit_system: "System Event Audit Logs",
  cloud_functions: "Cloud Functions Logs",
  cloud_monitoring: "Cloud Monitoring Alert Logs",
  firewall_logs: "Firewall Rule Logs",
  gce: "GCE Inventory",
  iam_policy: "IAM Snapshot",
  load_balancer: "Cloud Load Balancing Logs",
  cloud_cdn: "Cloud CDN Access Logs",
  logging_posture: "Logging Posture",
  login_events: "Login Audit Logs",
  network_posture: "Network Posture",
  project: "Project Context",
  scc_findings: "SCC Findings",
  vm_logs: "GCE VM Logs",
  gke_audit: "GKE Audit Logs",
  cloud_dns: "Cloud DNS Logs",
  cloud_armor: "Cloud Armor Logs",
  cloud_nat: "Cloud NAT Logs",
  k8s_apiserver_audit: "API-Server Audit Logs",
  k8s_audit_posture: "Audit Logging Posture",
  k8s_events: "Kubernetes Events",
  k8s_cluster_state: "Cluster Inventory",
  k8s_rbac: "RBAC Snapshot",
  k8s_container_logs: "Container Logs",
  k8s_kubelet_logs: "Kubelet Logs",
  k8s_runtime_logs: "CRI Logs",
  k8s_etcd: "etcd Logs + Posture",
  k8s_cni_logs: "CNI Plugin Logs",
  package: "Seal evidence package",
  ingest: "Ingest into case store",
};

export function displayArtifactLabel(collector: string, cloud?: string): string {
  const c = cloud?.toLowerCase();
  if (collector === "storage_access") {
    if (c === "gcp") return "GCS Access Logs";
    if (c === "aws") return "S3 Access Logs";
    return "Storage Access Logs";
  }
  if (ARTIFACT_DISPLAY_LABELS[collector]) return ARTIFACT_DISPLAY_LABELS[collector];
  const label = ARTIFACT_ICON_LABELS[collector] ?? collector.replace(/_/g, " ");
  return label.charAt(0).toUpperCase() + label.slice(1);
}

export function resolveArtifactIconLabel(_cloud: string, collector: string): string | null {
  return ARTIFACT_ICON_LABELS[collector] ?? null;
}

export function artifactIconSrc(cloud: string, collector: string): string | null {
  if (!ARTIFACT_ICON_LABELS[collector]) return null;
  const folder = cloud.toLowerCase();
  return `/icons/${folder}/${collector}.svg`;
}
